name: Run FastAPI Solve Every 15 Minutes (No Docker)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  solve-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install Python packages
        run: |
          pip install --no-cache-dir xvfbwrapper patchright fastapi[standard]
          python -m patchright install-deps chromium
          python -m patchright install chromium

      - name: Start FastAPI app in background
        run: |
          nohup python -m fastapi run app.py --port 5000 > server.log 2>&1 &
          sleep 10

      - name: Call /solve endpoint
        run: |
          echo "Calling /solve..."
          curl -X GET http://localhost:5000/solve

      - name: Call /solve endpoint
        run: |
          echo "Calling /solve..."
          curl -X GET http://localhost:5000/solve

      - name: Call /solve endpoint
        run: |
          echo "Calling /solve..."
          curl -X GET http://localhost:5000/solve

      - name: Output logs (optional)
        run: cat server.log
